#!/bin/bash

#创建根密钥
openssl ecparam -out ROOT_CA_PRIVATEKEY.key -name secp384r1 -genkey

#创建根证书CSR
openssl req -new -sha256 -key ROOT_CA_PRIVATEKEY.key -out ROOT_CA_CSR.csr -subj "/C=CN/ST=SH/L=PD/OU=XYZ_iOS/O=XYZ_iOS/CN=XYZ_IOS_CA"

#创建一个 CA 根证书的配置文件 
ROOT_CA_Path="./ROOT_CA.cnf"
(
cat << EOF
basicConstraints=critical,CA:TRUE
nsComment = "This Root certificate was generated by dadadongL"
keyUsage=critical, keyCertSign
subjectKeyIdentifier=hash
EOF
) > $ROOT_CA_Path

# 创建自签名CA
openssl x509 -req -sha256 -days 3650 -extfile $ROOT_CA_Path -in ROOT_CA_CSR.csr -signkey ROOT_CA_PRIVATEKEY.key -out ROOT_CA_CERT.crt


# ⚠️⚠️⚠️自签名的ip 记得改成自己的⚠️⚠️⚠️
ip_server="172.21.16.231"

# 创建证书的密钥 和 CSR 文件
openssl req -newkey rsa:2048 -nodes -subj "/C=CN/ST=SH/O=XYZ_iOS/OU=XYZ_iOS/CN=$ip_server" -keyout server-key.key -out server-csr.csr

# 2.1 创建一个配置文件  很重要!! 不然浏览器任然会提示不安全 NET::ERR_CERT_COMMON_NAME_INVALID
# 需要把签发的域名 或者IP地址 填到 [alt_names] 里面
ssl_cnf_path="./ssl.cnf"
(
cat << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
IP.1 = $ip_server
EOF
) > $ssl_cnf_path

# 签发 证书有效期最长为13个月 (398 天), 不然浏览器会显示不安全
openssl x509 -req -CA ROOT_CA_CERT.crt -CAkey ROOT_CA_PRIVATEKEY.key -CAcreateserial -days 365 -sha256 -extfile $ssl_cnf_path -in server-csr.csr -out server-crt.crt

# 校验
openssl verify -CAfile ROOT_CA_CERT.crt server-crt.crt
